name: raport
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.1
  getwidget: ^2.0.4
  shared_preferences: ^2.0.12
  toast: ^0.1.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

  assets:
    - assets/images/
